FROM php:8.1-cli

ARG BUILD_DATE
ARG VCS_REF

ENV COMPOSER_NO_INTERACTION=1
ENV COMPOSER_ALLOW_SUPERUSER=1

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/scriptor2k2/ci.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="scriptor2k2" \
      org.label-schema.name="scriptor2k2-ci" \
      org.label-schema.description="Docker for Laravel in a CI environment" \
      org.label-schema.url="https://github.com/scriptor2k2/ci"

RUN apt-get update

RUN apt-get -y install libreoffice --no-install-recommends --no-install-suggests

RUN apt-get install -y apt-utils
RUN apt-get install -y apt-transport-https gnupg

RUN apt-get update && apt-get install -y \
        libbz2-dev \
        libsodium-dev \
        libzip-dev \
        git \
        unzip \
        wget \
        libpng-dev \
        libgconf-2-4 \
        libfontconfig1 \
        chromium \
        xvfb \
        libmagickwand-dev \
        yarn

RUN docker-php-ext-install -j$(nproc) \
        bcmath \
        bz2 \
        calendar \
        intl \
        exif \
        gd \
        sodium \
        pcntl \
        pdo_mysql \
        shmop \
        sockets \
        sysvmsg \
        sysvsem \
        sysvshm \
        zip

RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev

RUN docker-php-ext-configure gd \
	--with-jpeg=/usr/include/ \
	--with-freetype=/usr/include/

RUN docker-php-ext-install -j$(nproc) gd

RUN pecl install redis
RUN docker-php-ext-enable redis

RUN pecl install imagick
RUN docker-php-ext-enable imagick

RUN pecl install pcov
RUN docker-php-ext-enable pcov

COPY ./scripts ./scripts

RUN ./scripts/composer.sh

RUN chmod +rx ./scripts/start.sh

ENTRYPOINT ["/scripts/start.sh"]
CMD ["php", "-a"]
